const PAGE_HTML = "__SITE_HTML__";
const ORGANIZATIONS_HTML = "__ORGANIZATIONS_HTML__";
const ABOUT_HTML = "__ABOUT_HTML__";
const MANAGE_HTML = "__MANAGE_HTML__";
const ASSETS = "__ASSETS__";
const ORIGINS = new Set(['https://superintelligencesg.org','https://www.superintelligencesg.org','https://superintelligencesg.com','https://www.superintelligencesg.com','https://superintelligencesg.ai','https://api.superintelligencesg.org','https://data.superintelligencesg.org']);
const CATEGORIES=['Organization','Research','Applied research','Education & research','Company','Health AI','Ecosystem','Governance','Public capability'];
const PUBLIC_SELECT=`SELECT o.id,o.name,o.founder,o.business,o.logo_key,o.created_at,d.website_url,d.location,d.category,d.collaboration,d.collaboration_note,d.contact_url,d.updated_at,d.verification_status,d.verified_domain,d.verified_at FROM organizations o LEFT JOIN organization_details d ON d.organization_id=o.id`;
function headers(origin,type='application/json; charset=utf-8'){const h=new Headers({'Content-Type':type,'Cache-Control':'no-store','X-Content-Type-Options':'nosniff','Referrer-Policy':'strict-origin-when-cross-origin'});if(ORIGINS.has(origin)){h.set('Access-Control-Allow-Origin',origin);h.set('Access-Control-Allow-Methods','GET, POST, OPTIONS');h.set('Access-Control-Allow-Headers','Content-Type, Authorization');h.set('Vary','Origin')}return h}function pageHeaders(){return new Headers({'Content-Type':'text/html; charset=utf-8','Cache-Control':'public, max-age=300, stale-while-revalidate=86400','X-Content-Type-Options':'nosniff','Referrer-Policy':'strict-origin-when-cross-origin'})}function assetHeaders(type){return new Headers({'Content-Type':type,'Cache-Control':'public, max-age=86400, stale-while-revalidate=604800','X-Content-Type-Options':'nosniff','Referrer-Policy':'strict-origin-when-cross-origin'})}
function json(d,s=200,o){return new Response(JSON.stringify(d),{status:s,headers:headers(o)})}
function fail(message,status=400){throw Object.assign(new Error(message),{status})}
const now=()=>Math.floor(Date.now()/1000);
async function hash(value){const bytes=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(value));return Array.from(new Uint8Array(bytes),b=>b.toString(16).padStart(2,'0')).join('')}
function secret(){return Array.from(crypto.getRandomValues(new Uint8Array(32)),b=>b.toString(16).padStart(2,'0')).join('')}
function base64(bytes){let str='';for(let i=0;i<bytes.length;i+=32768)str+=String.fromCharCode(...bytes.subarray(i,i+32768));return btoa(str)}
function validImage(b,t){return t==='image/png'?b.length>=8&&b[0]===137&&b[1]===80&&b[2]===78&&b[3]===71:t==='image/jpeg'?b.length>=3&&b[0]===255&&b[1]===216&&b[2]===255:t==='image/webp'?b.length>=12&&String.fromCharCode(...b.slice(0,4))==='RIFF'&&String.fromCharCode(...b.slice(8,12))==='WEBP':false}
async function imageData(file,required){if(!file||!file.size){if(required)fail('Upload your organisation logo.');return null}if(typeof file.arrayBuffer!=='function'||file.size>2097152)fail('Use a PNG, JPG or WebP logo up to 2 MB.');const b=new Uint8Array(await file.arrayBuffer());if(!validImage(b,file.type))fail('The logo is not a valid PNG, JPG or WebP image.');return 'data:'+file.type+';base64,'+base64(b)}
function text(value,max,required=false){const s=String(value||'').trim();if((required&&!s)||s.length>max)fail('Check the required fields and their character limits.');return s}
function website(value){if(!value)return '';try{const u=new URL(value);if(!['https:','http:'].includes(u.protocol)||u.username||u.password||u.port||!u.hostname.includes('.')||/^[\d.]+$/.test(u.hostname)||u.hostname.includes(':')||!/^[a-z0-9.-]+$/i.test(u.hostname)||u.hostname.endsWith('.local'))throw Error();return u.href}catch{fail('Enter a public website URL beginning with https:// or http://.')}}
function contact(value){if(!value)return '';try{const u=new URL(value);if(u.protocol==='mailto:'&&/^[^\s@?]+@[^\s@?]+\.[^\s@?]+$/.test(u.pathname)&&!u.search)return u.href;return website(value)}catch{fail('Use a public contact page URL or mailto:name@example.com.')}}
function inferredWebsite(business){const m=business.match(/https?:\/\/[^\s<>]+/);try{return m?website(m[0]):''}catch{return ''}}
function publicRow(row){return {...row,website_url:row.website_url??inferredWebsite(row.business),location:row.location||'',category:row.category||'Organization',collaboration:row.collaboration||'unspecified',collaboration_note:row.collaboration_note||'',contact_url:row.contact_url||'',verification_status:row.verification_status||'submitted',updated_at:row.updated_at||row.created_at}}
function fields(form){const category=text(form.get('category'),50)||'Organization',collaboration=text(form.get('collaboration'),20)||'unspecified';if(!CATEGORIES.includes(category)||!['unspecified','open','closed'].includes(collaboration))fail('Choose an available category and collaboration status.');return {name:text(form.get('name'),100,true),founder:text(form.get('founder'),100,true),business:text(form.get('business'),500,true),website_url:website(text(form.get('website_url'),300)),location:text(form.get('location'),120),category,collaboration,collaboration_note:text(form.get('collaboration_note'),300),contact_url:contact(text(form.get('contact_url'),300))}}
async function limited(request,env,action,limit=30){const key=await hash(action+':'+(request.headers.get('CF-Connecting-IP')||'unknown')),n=now();const result=await env.DB.batch([env.DB.prepare('INSERT INTO organization_rate_limits(ip_hash,created_at) VALUES(?,?)').bind(key,n),env.DB.prepare('SELECT COUNT(*) AS count FROM organization_rate_limits WHERE ip_hash=? AND created_at>?').bind(key,n-3600),env.DB.prepare('DELETE FROM organization_rate_limits WHERE created_at<?').bind(n-86400)]);if(Number(result[1].results[0]?.count)>limit)fail('Too many attempts. Please try again in one hour.',429)}
async function bodyJSON(request){if(Number(request.headers.get('Content-Length')||0)>10000)fail('Request is too large.',413);try{return await request.json()}catch{fail('Invalid request body.')}}
function orgID(value){if(typeof value!=='string'||!/^[a-f0-9-]{36}$/.test(value))fail('Choose a valid organisation profile.');return value}
async function owned(request,env,id){const value=request.headers.get('Authorization')||'';if(!/^Bearer [a-f0-9]{64}$/.test(value))fail('Enter the management key for this profile.',401);const row=await env.DB.prepare('SELECT * FROM organization_details WHERE organization_id=? AND manage_hash=?').bind(id,await hash(value.slice(7))).first();if(!row)fail('The management key does not match this profile.',401);return row}
async function readOne(env,id,includeWithdrawn=false){const row=await env.DB.prepare(PUBLIC_SELECT+' WHERE o.id=?'+(includeWithdrawn?'':' AND COALESCE(d.published,1)=1')).bind(id).first();if(!row)fail('This profile is unavailable.',404);return publicRow(row)}
export default {async fetch(request,env){const u=new URL(request.url),origin=request.headers.get('Origin'),path=u.pathname.startsWith('/directory/')?'/api/'+u.pathname.slice('/directory/'.length):u.pathname;
 const pages={'/':PAGE_HTML,'/index.html':PAGE_HTML,'/organizations.html':ORGANIZATIONS_HTML,'/about.html':ABOUT_HTML,'/manage.html':MANAGE_HTML};
 if(['GET','HEAD'].includes(request.method)&&(pages[u.pathname]||ASSETS[u.pathname])){const asset=ASSETS[u.pathname];const body=pages[u.pathname]||(asset?.base64?Uint8Array.from(atob(asset.base64),c=>c.charCodeAt(0)):asset?.body);return new Response(request.method==='HEAD'?null:body,{headers:asset?assetHeaders(asset.type):pageHeaders()})}
 if(!path.startsWith('/api/'))return new Response('Not found',{status:404});
 if(request.method==='OPTIONS')return new Response(null,{status:ORIGINS.has(origin)?204:403,headers:headers(origin)});
 if(origin&&!ORIGINS.has(origin))return json({error:'This origin is not allowed.'},403,origin);
 try{
 if(path==='/api/organizations'&&request.method==='GET'){const result=await env.DB.prepare(PUBLIC_SELECT+' WHERE COALESCE(d.published,1)=1 ORDER BY o.created_at DESC LIMIT 500').all();return json({organizations:(result.results||[]).map(publicRow)},200,origin)}
 if(path.startsWith('/api/shortlists/')&&request.method==='GET'){const id=orgID(path.split('/').pop());const row=await env.DB.prepare('SELECT entry_ids,created_at FROM navigator_shortlists WHERE id=?').bind(id).first();if(!row)fail('This shortlist is unavailable.',404);return json({ids:JSON.parse(row.entry_ids),created_at:row.created_at},200,origin)}
 if(request.method!=='POST')return json({error:'Not found'},404,origin);
 if(!ORIGINS.has(origin))fail('Open this form from the Commons website.',403);
 if(path==='/api/shortlists'){await limited(request,env,'shortlist',120);const data=await bodyJSON(request);if(!Array.isArray(data.ids)||data.ids.length>6||data.ids.some(id=>typeof id!=='string'||!/^[a-zA-Z0-9-]{1,100}$/.test(id)))fail('Save up to 6 valid directory entries.');const id=crypto.randomUUID();await env.DB.prepare('INSERT INTO navigator_shortlists(id,entry_ids,created_at) VALUES(?,?,?)').bind(id,JSON.stringify([...new Set(data.ids)]),now()).run();return json({id},201,origin)}
 if(path==='/api/organizations'){
  await limited(request,env,'publish',5);if(Number(request.headers.get('Content-Length')||0)>2200000)fail('The logo must be no larger than 2 MB.',413);
  const form=await request.formData();if(String(form.get('website')||'').trim())fail('Unable to submit this entry.');if(form.get('consent')!=='on')fail('Confirm that you represent the organisation and may publish these details.');const f=fields(form),logo=await imageData(form.get('logo'),true),id=crypto.randomUUID(),key=secret(),n=now();
  await env.DB.batch([env.DB.prepare('INSERT INTO organizations(id,name,founder,business,logo_key,created_at) VALUES(?,?,?,?,?,?)').bind(id,f.name,f.founder,f.business,logo,n),env.DB.prepare('INSERT INTO organization_details(organization_id,website_url,location,category,collaboration,collaboration_note,contact_url,manage_hash,updated_at) VALUES(?,?,?,?,?,?,?,?,?)').bind(id,f.website_url,f.location,f.category,f.collaboration,f.collaboration_note,f.contact_url,await hash(key),n)]);
  return json({ok:true,organization:await readOne(env,id),management_key:key},201,origin);
 }
 if(path.startsWith('/api/manage/')){
  await limited(request,env,'manage');
  if(path==='/api/manage/update'){
   if(Number(request.headers.get('Content-Length')||0)>2200000)fail('The logo must be no larger than 2 MB.',413);const form=await request.formData(),id=orgID(form.get('id')),owner=await owned(request,env,id),f=fields(form),logo=await imageData(form.get('logo'),false),old=await readOne(env,id,true),sameDomain=owner.verified_domain&&f.website_url&&new URL(f.website_url).hostname===owner.verified_domain;
   await env.DB.batch([env.DB.prepare('UPDATE organizations SET name=?,founder=?,business=?,logo_key=? WHERE id=?').bind(f.name,f.founder,f.business,logo||old.logo_key,id),env.DB.prepare('UPDATE organization_details SET website_url=?,location=?,category=?,collaboration=?,collaboration_note=?,contact_url=?,updated_at=?,verification_status=?,verified_domain=?,verified_at=?,claim_hash=NULL,claim_challenge=NULL,claim_expires=NULL WHERE organization_id=?').bind(f.website_url,f.location,f.category,f.collaboration,f.collaboration_note,f.contact_url,now(),sameDomain?'claimed':'submitted',sameDomain?owner.verified_domain:null,sameDomain?owner.verified_at:null,id)]);return json({ok:true,organization:await readOne(env,id,true)},200,origin);
  }
  const data=await bodyJSON(request),id=orgID(data.id),owner=await owned(request,env,id);
  if(path==='/api/manage/read')return json({organization:await readOne(env,id,true),published:owner.published===1},200,origin);
  if(path==='/api/manage/visibility'){if(typeof data.published!=='boolean')fail('Choose a visibility setting.');await env.DB.prepare('UPDATE organization_details SET published=?,updated_at=? WHERE organization_id=?').bind(data.published?1:0,now(),id).run();return json({ok:true,published:data.published},200,origin)}
  if(path==='/api/manage/rotate'){const key=secret();await env.DB.prepare('UPDATE organization_details SET manage_hash=? WHERE organization_id=?').bind(await hash(key),id).run();return json({ok:true,management_key:key},200,origin)}
 }
 if(path==='/api/claim/start'){
  await limited(request,env,'claim-start',8);const data=await bodyJSON(request),id=orgID(data.id),row=await readOne(env,id,true),url=row.website_url;if(!url)fail('No website is recorded. Contact the editor to establish the website from a public source before claiming.',409);const domain=new URL(url).hostname,privateKey=secret(),challenge='sg-commons='+secret(),expires=now()+86400;
  await env.DB.prepare(`INSERT INTO organization_details(organization_id,website_url,claim_hash,claim_challenge,claim_expires) VALUES(?,?,?,?,?) ON CONFLICT(organization_id) DO UPDATE SET claim_hash=excluded.claim_hash,claim_challenge=excluded.claim_challenge,claim_expires=excluded.claim_expires`).bind(id,url,await hash(privateKey),challenge,expires).run();return json({domain,record_name:'_sg-commons.'+domain,record_type:'TXT',record_value:challenge,claim_key:privateKey,expires_at:expires},200,origin);
 }
 if(path==='/api/claim/verify'){
  await limited(request,env,'claim-verify',15);const data=await bodyJSON(request),id=orgID(data.id);if(!/^[a-f0-9]{64}$/.test(data.claim_key||''))fail('Enter your private claim key.',401);const claimHash=await hash(data.claim_key),d=await env.DB.prepare('SELECT * FROM organization_details WHERE organization_id=? AND claim_hash=? AND claim_expires>?').bind(id,claimHash,now()).first();if(!d)fail('This claim has expired or was replaced. Start a new claim.',401);const domain=new URL(d.website_url).hostname;
  const dns=await fetch('https://cloudflare-dns.com/dns-query?name='+encodeURIComponent('_sg-commons.'+domain)+'&type=TXT',{headers:{accept:'application/dns-json'},signal:AbortSignal.timeout(8000)});if(!dns.ok)fail('DNS lookup is temporarily unavailable. Try again shortly.',503);const answer=await dns.json();if(answer.Status!==0||!answer.Answer?.some(r=>r.type===16&&r.data.replace(/"\s*"/g,'').replace(/^"|"$/g,'')===d.claim_challenge))fail('The matching TXT record is not visible yet. Check the record and allow time for DNS to update.',409);
  const key=secret(),n=now();const result=await env.DB.prepare("UPDATE organization_details SET manage_hash=?,verification_status='claimed',verified_domain=?,verified_at=?,updated_at=?,claim_hash=NULL,claim_challenge=NULL,claim_expires=NULL WHERE organization_id=? AND claim_hash=? AND claim_expires>?").bind(await hash(key),domain,n,n,id,claimHash,n).run();if(result.meta?.changes!==1)fail('This claim has already been completed or expired.',409);return json({ok:true,management_key:key,verified_domain:domain},200,origin);
 }
 return json({error:'Not found'},404,origin);
 }catch(error){if(error.status)return json({error:error.message},error.status,origin);console.error('Commons request failed',path);return json({error:'The service is temporarily unavailable. Keep your details and retry. If you just published, check the directory before submitting again.'},503,origin)}
}};
