const PAGE_HTML = "__SITE_HTML__";
const ALLOWED_ORIGINS = new Set(["https://superintelligencesg.org","https://www.superintelligencesg.org","https://superintelligence-sg-org.red-fun-plan-2664.chatgpt.site"]);
function headers(origin){const h=new Headers({"Content-Type":"application/json; charset=utf-8","Cache-Control":"no-store","X-Content-Type-Options":"nosniff"});if(origin&&ALLOWED_ORIGINS.has(origin)){h.set("Access-Control-Allow-Origin",origin);h.set("Access-Control-Allow-Methods","GET, POST, OPTIONS");h.set("Access-Control-Allow-Headers","Content-Type");h.set("Vary","Origin");}return h}
function json(d,s,o){return new Response(JSON.stringify(d),{status:s,headers:headers(o)})}
function validImage(b,t){if(t==="image/png")return b.length>=8&&b[0]===137&&b[1]===80&&b[2]===78&&b[3]===71;if(t==="image/jpeg")return b.length>=3&&b[0]===255&&b[1]===216&&b[2]===255;if(t==="image/webp")return b.length>=12&&String.fromCharCode(...b.slice(0,4))==="RIFF"&&String.fromCharCode(...b.slice(8,12))==="WEBP";return false}
async function rateKey(ip){const d=await crypto.subtle.digest("SHA-256",new TextEncoder().encode(ip||"unknown"));return Array.from(new Uint8Array(d),x=>x.toString(16).padStart(2,"0")).join("")}
export default {async fetch(request,env){const u=new URL(request.url),o=request.headers.get("Origin");if(u.pathname==="/"&&request.method==="GET")return new Response(PAGE_HTML,{headers:{"Content-Type":"text/html; charset=utf-8","Cache-Control":"no-cache","X-Content-Type-Options":"nosniff"}});if(!u.pathname.startsWith("/api/"))return new Response("Not found",{status:404});if(request.method==="OPTIONS"){if(!o||!ALLOWED_ORIGINS.has(o))return new Response(null,{status:403});return new Response(null,{status:204,headers:headers(o)})}if(o&&!ALLOWED_ORIGINS.has(o))return json({error:"This website is not allowed to submit directory entries."},403,o);try{
if(u.pathname==="/api/organizations"&&request.method==="GET"){const r=await env.DB.prepare("SELECT id,name,founder,business,logo_key,created_at FROM organizations ORDER BY created_at DESC LIMIT 100").all();return json({organizations:r.results||[]},200,o)}
if(u.pathname==="/api/organizations"&&request.method==="POST"){if(!o||!ALLOWED_ORIGINS.has(o))return json({error:"Open the form from the Superintelligence SG Commons website."},403,o);if(Number(request.headers.get("Content-Length")||0)>2200000)return json({error:"The logo must be no larger than 2 MB."},413,o);const f=await request.formData();if(String(f.get("website")||"").trim())return json({error:"Unable to submit this entry."},400,o);if(f.get("consent")!=="on")return json({error:"Please confirm that these details can be published."},400,o);const name=String(f.get("name")||"").trim(),founder=String(f.get("founder")||"").trim(),business=String(f.get("business")||"").trim(),logo=f.get("logo");if(!name||name.length>100||!founder||founder.length>100||!business||business.length>500)return json({error:"Check the organization name, founder and core work fields."},400,o);if(!logo||typeof logo.arrayBuffer!=="function"||logo.size>2097152)return json({error:"Choose a logo no larger than 2 MB."},400,o);const type=logo.type,bytes=new Uint8Array(await logo.arrayBuffer());if(!validImage(bytes,type))return json({error:"Use a valid PNG, JPG or WebP image."},400,o);const now=Math.floor(Date.now()/1000),hash=await rateKey(request.headers.get("CF-Connecting-IP")||""),recent=await env.DB.prepare("SELECT COUNT(*) AS count FROM organization_rate_limits WHERE ip_hash=? AND created_at>?").bind(hash,now-3600).first();if(Number(recent?.count||0)>=5)return json({error:"Please wait a little before submitting another organization."},429,o);const id=crypto.randomUUID(),logoData="data:"+type+";base64,"+btoa(String.fromCharCode(...bytes));await env.DB.batch([env.DB.prepare("INSERT INTO organization_rate_limits(ip_hash,created_at) VALUES(?,?)").bind(hash,now),env.DB.prepare("DELETE FROM organization_rate_limits WHERE created_at<?").bind(now-86400),env.DB.prepare("INSERT INTO organizations(id,name,founder,business,logo_key,created_at) VALUES(?,?,?,?,?,?)").bind(id,name,founder,business,logoData,now)]);return json({ok:true,organization:{id,name,founder,business,logo_key:logoData,created_at:now}},201,o)}
return new Response("Not found",{status:404})}catch(e){console.error("Organization directory request failed:",e);return json({error:"The directory is temporarily unavailable. Your information has not been published."},503,o)}}};
